name: spring-test

server:
  port: 8086

druid:
  url: jdbc:mariadb://localhost:3306/test
  username: root
  password: 123456
  initialSize: 1
  minIdle: 3
  maxActive: 20
  maxWait: 60000
  validationQuery: SELECT 'x' FROM DUAL

mybatis:
  configuration:
    #开启下划线到驼峰的自动转换，将数据库字段根据驼峰规则注入到对象属性
    map-underscore-to-camel-case: true
#  mapperLocations:
#    - classpath*:sqlmap/*Mapper.xml
mapper:
  mappers: com.phuag.sample.common.persistence.BaseDao

pagehlper:
  reasonable: true
  params: count-countSql

shiro:
  realmClass: com.phuag.sample.common.security.shiro.UserPasswordDBRealm
  multiAccountLogin: false
  loginUrl: /api/sysUser/login
#  successUrl: /main.html#/main
#  unauthorizedUrl: /main.html#/404
  filterChainDefinitions:
     /druid/*: anon
     swagger-ui.html*: anon
     /bower_components/**: anon
     /js/**: anon
     /css/**: anon
     /images/**: anon
     /partials/**: anon
     /i18n/**: anon
     /api/ping: anon
     /api/sysUser/login: anon
     /main.html#/register: anon
     /main.html#/login: authcBasic
     /api/sysUser/me: authcBasic
#     /api/logout: logout
     /api/**: user
     /main.html#/**: user

logging:
  file: app.log
  maxFileSize: 10KB
  level:
    root: INFO
    org.springfamework.web: INFO
    com.phuag.sample: DEBUG
    com.alibaba.druid: DEBUG